users:
  ss:
    username: ss
    articleIds: []
    commentIds: []
  as:
    username: as
    articleIds:
      - 1
    commentIds:
      - 1
articles:
  '1':
    id: 1
    title: ss
    url: ff
    username: as
    commentIds:
      - 1
    upvotedBy: []
    downvotedBy: []
    comments:
      - &ref_0
        id: 1
        body: ffff
        username: as
        articleId: 1
        upvotedBy: []
        downvotedBy: []
comments:
  '1': *ref_0
nextArticleId: 2
nextCommentId: 2
